added benchmarks for G_T
filecoin-project/blstrs pull request #59
Opened 2024-07-09 15:14 UTC by alinush

Added some missing benchmarks for $\mathbb{G}_T$ operations.

**Note:** The `rust_toolchain` file and the hardcoded version in `Cargo.toml` caused problems for me. However, I can revert those changes if need be.

2024-07-15 09:21 UTC, vmx requested changes
Thanks, this looks good! Running the benchmarks need a nightly Rust, so the 1.56.1 isn't a problem there. What were you issues? I'd prefer if we keep the version in the `Cargo.toml` and the `rust-toolchain` file.

Please also run `cargo fmt` for consistent formatting.

2024-07-15 09:40 UTC, vmx commented
I now also see an error locally on master. I'll have a look (it should be independent of this PR).

2024-09-28 18:27 UTC, alinush commented
Rebased and formatted with `cargo fmt`!

2024-09-30 18:15 UTC, vmx approved these changes
Thanks!

2024-09-30 18:16 UTC, merged